# Generated by Django 3.1 on 2022-05-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220413_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'shipping address', 'verbose_name_plural': 'shipping addresses'},
        ),
    ]
